name: CI/CD project

on: push

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: social_media
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_PORT: 3306
      DB_HOST: localhost

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.4'

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE social_media;' -uroot -proot

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Clear Config
        run: php artisan config:clear

      - name: Execute check coding convetion via PHP Code Sniffer
        run: ./vendor/bin/phpcs

      - name: Run Migration
        run:
          php artisan migrate -v
        env:
          DB_PORT: ${{ env.DB_PORT }}

      - name: Run Seeder
        run:
          php artisan db:seed
        env:
          DB_PORT: ${{ env.DB_PORT }}

      - name: Test with phpunit
        run: vendor/bin/phpunit
        env:
          DB_PORT: ${{ env.DB_PORT }}
